### ISSUE TITLE
return_passages option returns incorrect passages

### ISSUE THREAD

**Issue by LuciaCam** [genthalili/searoute-py#35] opened 2024-06-12 15:51 UTC
Hello,

I have tried to use the return_passages new feature, but it is returning passages that aren't crossed by the maritime path.
Here is an example:

```
import searoute as sr
import geopandas as gpd
import folium

traj = sr.searoute([52.99, 25.01], [-61.87, 17.15], append_orig_dest=True, restrictions=['northwest', 'chili'], return_passages=True)
print(traj['properties']['traversed_passages'])

gdf = gpd.GeoDataFrame.from_features([traj])
gdf = gdf.set_crs("EPSG:4326")
m = folium.Map(location=[0, 0], zoom_start=2)
folium.GeoJson(gdf).add_to(m)
m
```

The resulting traversed passages are:

`['gibraltar', 'panama', 'sunda', 'malacca', 'ormuz', 'chili', 'suez', 'bosporus', 'babalmandab', 'south_africa']`

When they should only be:

`['gibraltar', 'suez', 'babalmandab', 'ormuz']`

Here is a picture of the trajectory:
![image](https://github.com/genthalili/searoute-py/assets/114501538/188afa2d-a5ec-493a-8102-7cc0a5021731)

Thank you for your help!

**Comment by genthalili** [comment] 2024-06-22 10:22
Hi @LuciaCam , true, looks like the the new version is not fixing it. 
Will commit the new patch soon.

**Comment by LuciaCam** [comment] 2024-06-24 07:22
Thanks for the prompt response and fix @genthalili , awesome job!

**Comment by LuciaCam** [comment] 2024-08-05 14:14
Hello again!
The fix for returning passages is now correct most of the time, but there are still cases for which it does not return the correct traversed passages:

```
import searoute as sr
import geopandas as gpd
import folium

traj = sr.searoute([140.02, 35.51], [-97.36, 27.81], append_orig_dest=True, return_passages=True)
print(traj['properties']['traversed_passages'])

gdf = gpd.GeoDataFrame.from_features([traj])
gdf = gdf.set_crs("EPSG:4326")
m = folium.Map(location=[0, 180], zoom_start=3)
folium.GeoJson(gdf).add_to(m)
m
```

This code chunk should return that `panama` has been crossed, but it returns an empty list of passages instead. Here is a picture of the trajectory:

![image](https://github.com/user-attachments/assets/fd90236c-f332-4d5f-a798-40fd2c67af8c)

I am using searoute 1.4.1, the latest release available from pip.

**Comment by dcwtx** [comment] 2024-08-05 20:57
Hi, this is terrific.  But it should be 'chile' not 'chili'.

**Comment by genthalili** [comment] 2024-08-05 22:00
I was able to reproduce the issue, as you mentioned the reason is due to the "normalisation" of the lat/lon  when crossing from <-180 to 180.

Should be fixed in the next release.

**Comment by genthalili** [comment] 2024-08-05 22:07
For the `chili`, I used the french name for Chile which is Chili,  as I wanted to differentiate the country to the strait, but somehow keep it simple, the correct name should be `magellan`, as this is called : [Strait of Magellan ](https://en.wikipedia.org/wiki/Strait_of_Magellan) :)

Most probably should change this to `magellan`!

**Comment by dcwtx** [comment] 2024-08-05 22:09
Probably - I’m from Texas and chili is, well you know - chili!

'magellan'

**Comment by genthalili** [comment] 2024-08-05 22:15
https://www.thespruceeats.com/different-spellings-of-chile-2342844

**Comment by genthalili** [comment] 2024-08-18 19:58
@LuciaCam, could you please check with the new release version `1.4.2` and let me know if this is fixing the bug?

**Comment by LuciaCam** [comment] 2024-08-19 07:56
@genthalili The new release has fixed the issue for me! Thanks again 👍

**Closed** 2024-10-29 11:14 UTC
Labels: bug
